"""M1 smoke test: upload one real fixture file pair per client (generated by
the synthetic generator), run ingestion+normalization only, and confirm the
batch reaches NORMALIZED with correctly resolved transactions/identifiers."""
from datetime import date
from pathlib import Path

from app.synthetic import generator as gen
from app.synthetic import scenarios as sc

CONFIGS_ROOT = Path(__file__).resolve().parents[2] / "configs" / "clients"


def _load_yaml(client_code: str) -> str:
    return (CONFIGS_ROOT / client_code / "v1.yaml").read_text(encoding="utf-8")


def _setup_client_and_batch(api_client, tmp_path, client_code: str, scenarios: list[sc.Scenario]):
    resp = api_client.post("/api/v1/clients", json={"code": client_code, "name": client_code})
    client_id = resp.json()["id"]
    api_client.post(f"/api/v1/clients/{client_id}/config-versions", json={"raw_yaml": _load_yaml(client_code)})
    api_client.post(f"/api/v1/clients/{client_id}/config-versions/1/activate")

    batch_code = f"{client_code}-m1"
    resp = api_client.post(f"/api/v1/clients/{client_id}/batches", json={"batch_code": batch_code})
    batch_id = resp.json()["id"]

    written = gen.generate_batch_files(scenarios, client_code, batch_code, tmp_path)
    for source_id, path in written.items():
        with path.open("rb") as f:
            resp = api_client.post(
                f"/api/v1/batches/{batch_id}/files",
                params={"source_id": source_id},
                files={"file": (path.name, f)},
            )
        assert resp.status_code == 200, resp.text

    return client_id, batch_id


def test_client_a_ingestion_and_normalization(api_client, tmp_path):
    scenarios = [
        sc.client_a_exact_match(1, date(2026, 9, 1), __import__("random").Random(1)),
        sc.client_a_exact_match(2, date(2026, 9, 1), __import__("random").Random(2)),
        sc.client_a_normalized_reference_match(1, date(2026, 9, 1), __import__("random").Random(3)),
    ]
    client_id, batch_id = _setup_client_and_batch(api_client, tmp_path, "client_a", scenarios)

    resp = api_client.post(f"/api/v1/batches/{batch_id}/files/complete")
    assert resp.status_code == 200, resp.text
    assert resp.json()["status"] == "FILES_RECEIVED"

    resp = api_client.post(f"/api/v1/batches/{batch_id}/process")
    assert resp.status_code == 200, resp.text
    batch = resp.json()
    # /process now runs ingestion -> normalization -> reconciliation (M2); this
    # test only asserts the M1 (normalization) part of that chain succeeded.
    assert batch["normalized_at"] is not None
    assert batch["status"] == "CLOSED", batch

    resp = api_client.get(f"/api/v1/batches/{batch_id}/transactions")
    txns = resp.json()
    assert len(txns) == 6  # 3 scenarios x 2 sources each

    internal_exact = [t for t in txns if t["source_id"] == "internal_ledger" and t["canonical_reference"]]
    assert len(internal_exact) == 3
    # exact-match scenario: internal Trade_ID should equal the bank UTR verbatim
    exact_internal = next(t for t in txns if t["source_id"] == "internal_ledger" and t["amount"])
    trade_id_identifiers = [i for i in exact_internal["identifiers"] if i["identifier_type"] == "TRADE_ID"]
    assert trade_id_identifiers, exact_internal

    # the UTR->TRADE_ID identifier_linkage rule should be recorded on the identifier
    utr_linked = [i for i in trade_id_identifiers if i["linked_via_rule_id"] == "LINK_UTR_TO_TRADE_ID"]
    assert utr_linked or trade_id_identifiers[0]["value_normalized"] == "", txns


def test_client_b_ingestion_and_normalization(api_client, tmp_path):
    scenarios = [
        sc.client_b_exact_match(1, date(2026, 9, 1), __import__("random").Random(11)),
        sc.client_b_exact_match(2, date(2026, 9, 1), __import__("random").Random(12)),
    ]
    client_id, batch_id = _setup_client_and_batch(api_client, tmp_path, "client_b", scenarios)

    api_client.post(f"/api/v1/batches/{batch_id}/files/complete")
    resp = api_client.post(f"/api/v1/batches/{batch_id}/process")
    assert resp.status_code == 200, resp.text
    assert resp.json()["normalized_at"] is not None

    resp = api_client.get(f"/api/v1/batches/{batch_id}/transactions")
    txns = resp.json()
    assert len(txns) == 4  # 2 scenarios x 2 sources

    gateway_txns = [t for t in txns if t["source_id"] == "payment_gateway"]
    for t in gateway_txns:
        order_ids = [i for i in t["identifiers"] if i["identifier_type"] == "ORDER_ID"]
        pg_txn_ids = [i for i in t["identifiers"] if i["identifier_type"] == "PG_TXN_ID"]
        assert order_ids and pg_txn_ids
        # PG_TXN_ID must NOT be treated as linked to anything (no configured rule)
        assert pg_txn_ids[0]["linked_via_rule_id"] is None
        # ORDER_ID is the configured linkage and should be the canonical_reference
        assert t["canonical_reference"] == order_ids[0]["value_normalized"]
