"""CLI + reusable functions to generate synthetic raw files (and their ground
truth) for Client A and Client B. Reused directly by integration tests so
fixtures and the demo dataset are generated by the same code path.

Usage: python -m app.synthetic.generator --seed 42 --output-dir <path>
"""
import argparse
import csv
import json
import random
from dataclasses import asdict
from datetime import date
from pathlib import Path

import pandas as pd

from app.synthetic import scenarios as sc

_FILENAMES = {
    ("client_a", "internal_ledger"): "internal_ledger.xlsx",
    ("client_a", "bank_statement"): "bank_statement.csv",
    ("client_b", "internal_ledger"): "internal_ledger.csv",
    ("client_b", "payment_gateway"): "payment_gateway.json",
}


def default_scenarios(seed: int, base_date: date, filler_count: int = 15) -> list[sc.Scenario]:
    rng = random.Random(seed)
    out: list[sc.Scenario] = []

    for i in range(1, filler_count + 1):
        out.append(sc.client_a_exact_match(i, base_date, rng))
    out.append(sc.client_a_normalized_reference_match(1, base_date, rng))
    out.append(sc.client_a_normalized_reference_match(2, base_date, rng))
    out.append(sc.client_a_timing_difference(1, base_date, rng))
    out.append(sc.client_a_timing_difference(2, base_date, rng))
    out.append(sc.client_a_counterparty_variation(1, base_date, rng))
    out.append(sc.client_a_counterparty_variation(2, base_date, rng))
    out.append(sc.client_a_split_settlement_one_to_many(1, base_date, rng))
    out.append(sc.client_a_missing_external_record(1, base_date, rng))
    out.append(sc.client_a_missing_internal_record(1, base_date, rng))
    out.append(sc.client_a_duplicate_posting(1, base_date, rng))
    out.append(sc.client_a_ambiguous_candidate(1, base_date, rng))

    for i in range(1, filler_count + 1):
        out.append(sc.client_b_exact_match(i, base_date, rng))
    out.append(sc.client_b_fee_adjusted_settlement(1, base_date, rng))
    out.append(sc.client_b_bundled_settlement_many_to_one(1, base_date, rng))
    out.append(sc.client_b_reference_matched_unexplained_variance(1, base_date, rng))

    return out


def _rows_by_source_for_client(scenarios: list[sc.Scenario], client_code: str) -> dict[str, list[dict]]:
    rows: dict[str, list[dict]] = {}
    for scenario in scenarios:
        if scenario.client_code != client_code:
            continue
        for source_id, source_rows in scenario.rows_by_source.items():
            rows.setdefault(source_id, []).extend(source_rows)
    return rows


def _all_columns(rows: list[dict]) -> list[str]:
    """Preserves first-seen column order across all rows -- not every
    scenario populates every optional column (e.g. a settlement batch
    reference), so the fieldnames/DataFrame columns must be the union, not
    just whatever the first row happens to have."""
    columns: dict[str, None] = {}
    for row in rows:
        for key in row:
            columns[key] = None
    return list(columns.keys())


def _write_source_file(client_code: str, source_id: str, rows: list[dict], directory: Path) -> Path:
    filename = _FILENAMES[(client_code, source_id)]
    path = directory / filename
    columns = _all_columns(rows)
    if filename.endswith(".csv"):
        with path.open("w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=columns, restval="")
            writer.writeheader()
            writer.writerows(rows)
    elif filename.endswith(".xlsx"):
        pd.DataFrame(rows, columns=columns).fillna("").to_excel(path, sheet_name="Transactions", index=False)
    elif filename.endswith(".json"):
        path.write_text(json.dumps(rows, indent=2), encoding="utf-8")
    else:
        raise ValueError(f"unsupported filename extension for {filename}")
    return path


def generate_batch_files(
    scenarios: list[sc.Scenario], client_code: str, batch_code: str, output_root: Path
) -> dict[str, Path]:
    rows_by_source = _rows_by_source_for_client(scenarios, client_code)
    written: dict[str, Path] = {}
    for source_id, rows in rows_by_source.items():
        directory = output_root / client_code / batch_code / source_id
        directory.mkdir(parents=True, exist_ok=True)
        written[source_id] = _write_source_file(client_code, source_id, rows, directory)
    return written


def write_ground_truth(scenarios: list[sc.Scenario], client_code: str, batch_code: str, output_root: Path) -> Path:
    entries = [
        {
            "economic_transaction_id": s.economic_transaction_id,
            "scenario_name": s.scenario_name,
            "expected_match_group": s.expected_match_group,
            "expected_exception_type": s.expected_exception_type,
            "expected_cardinality": s.expected_cardinality,
        }
        for s in scenarios
        if s.client_code == client_code
    ]
    directory = output_root / client_code / batch_code
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / "ground_truth.json"
    path.write_text(json.dumps(entries, indent=2), encoding="utf-8")
    return path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--output-dir", type=Path, default=Path("data/raw"))
    parser.add_argument("--batch-code", type=str, default="2026-09-01")
    parser.add_argument("--filler-count", type=int, default=15)
    args = parser.parse_args()

    all_scenarios = default_scenarios(args.seed, date(2026, 9, 1), args.filler_count)
    for client_code in ("client_a", "client_b"):
        written = generate_batch_files(all_scenarios, client_code, args.batch_code, args.output_dir)
        gt_path = write_ground_truth(all_scenarios, client_code, args.batch_code, args.output_dir.parent / "ground_truth")
        print(f"{client_code}: wrote {list(written.values())}, ground truth at {gt_path}")


if __name__ == "__main__":
    main()
